apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: fleet
spec:
  version: {{ .TagName }}
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/mhausenblas/kcf/releases/download/{{ .TagName }}/fleet_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "./fleet"
      to: "."
    - from: "./LICENSE"
      to: "."
    bin: "fleet"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/mhausenblas/kcf/releases/download/{{ .TagName }}/fleet_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "./fleet"
      to: "."
    - from: "./LICENSE"
      to: "."
    bin: "fleet"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/mhausenblas/kcf/releases/download/{{ .TagName }}/fleet_windows_amd64.zip" .TagName }}
    files:
    - from: "/fleet.exe"
      to: "."
    - from: "./LICENSE"
      to: "."
    bin: "fleet.exe"
  shortDescription: Shows config and resources of a fleet of clusters
  homepage: https://github.com/mhausenblas/kcf
  caveats: |
    Usage:
      $ kubectl fleet

    For additional options:
      $ kubectl fleet --help
      or https://github.com/mhausenblas/kcf/blob/v0.1.4/doc/USAGE.md

  description: |
    Allows to get an overview and details on a fleet of Kubernetes clusters.
    The top-level command lists all active clusters found in the kubeconfig provided.
    For each cluster, configuration info such as the control plane version or 
    API server endpoint are displayed, as well as select stats, for example, 
    the number of worker nodes or namespaces found in the cluster.
